# -*- coding: utf-8 -*-
"""exercicio_scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPP70hz39S3Xutx8QZ3Xg6R1cxcSFy1n

# **EXERCÍCIO DE WEB SCRAPING EM PYTHON**
*Site: books.toscrape.com (feito para praticar, sem bloqueios)*

**OBJETIVO:** Extrair livros do site e salvar em CSV.

*O exercício tem 3 partes:*

1.   Scraping básico (1 página)
2.   Scraping com múltiplas páginas
3.   Scraping com threads (paralelismo)
"""

!pip install requests beautifulsoup4

import requests
import time
import csv
import concurrent.futures
import threading
from bs4 import BeautifulSoup

BASE_URL = 'https://books.toscrape.com/'
headers = {'User-Agent': 'Mozilla/5.0'}

"""# **PARTE 1 — SCRAPING BÁSICO (1 página)**

**Conceitos:**
- requests.get() → faz a requisição HTTP
- BeautifulSoup() → parseia o HTML retornado
- find() → acha o PRIMEIRO elemento
- find_all() → acha TODOS os elementos
- get_text() → pega o texto dentro da tag
- get('atributo') → pega o valor de um atributo HTML
"""

def extrair_livros_pagina(url):
    """Extrai todos os livros de UMA página."""
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    livros = []

    # Cada livro está dentro de um <article class="product_pod">
    articles = soup.find_all('article', class_='product_pod')

    for article in articles:
        # Título está no atributo 'title' da tag <a> dentro de <h3>
        titulo = article.find('h3').find('a').get('title')

        # Preço está dentro de <p class="price_color">
        preco = article.find('p', class_='price_color').get_text()

        # Disponibilidade está dentro de <p class="instock availability">
        disponibilidade = article.find('p', class_='instock').get_text().strip()

        # Rating está como classe CSS na tag <p class="star-rating X">
        # Ex: "star-rating Three" → pegamos a segunda palavra
        rating_tag = article.find('p', class_='star-rating')
        rating = rating_tag['class'][1]  # "One", "Two", "Three", "Four", "Five"

        livros.append({
            'titulo': titulo,
            'preco': preco,
            'disponibilidade': disponibilidade,
            'rating': rating,
        })

    return livros


def parte1():
    print("=" * 50)
    print("PARTE 1 — Scraping de 1 página")
    print("=" * 50)

    livros = extrair_livros_pagina(BASE_URL)

    print(f"Livros encontrados: {len(livros)}\n")
    for livro in livros[:5]:  # Mostra os primeiros 5
        print(f"  📚 {livro['titulo']}")
        print(f"     Preço: {livro['preco']} | Rating: {livro['rating']} | {livro['disponibilidade']}")
        print()

parte1()

"""# **PARTE 2 — MÚLTIPLAS PÁGINAS**

**Conceitos novos:**
- Navegação entre páginas (paginação)
- Loop while para percorrer todas as páginas
- Salvar resultado em CSV com o módulo csv
"""

def extrair_proxima_pagina(soup):
    """Retorna a URL da próxima página, ou None se for a última."""
    next_btn = soup.find('li', class_='next')
    if next_btn:
        next_href = next_btn.find('a').get('href')
        # As páginas seguintes ficam em /catalogue/page-X.html
        if 'catalogue/' in next_href:
            return BASE_URL + next_href
        else:
            return BASE_URL + 'catalogue/' + next_href
    return None


def salvar_csv(livros, nome_arquivo='livros.csv'):
    """Salva a lista de livros em um arquivo CSV."""
    with open(nome_arquivo, mode='w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=['titulo', 'preco', 'disponibilidade', 'rating'])
        writer.writeheader()
        writer.writerows(livros)
    print(f"\n✅ Arquivo salvo: {nome_arquivo} ({len(livros)} livros)")


def parte2(max_paginas=5):
    print("=" * 50)
    print(f"PARTE 2 — Scraping de até {max_paginas} páginas")
    print("=" * 50)

    todos_livros = []
    url_atual = BASE_URL
    pagina = 1

    while url_atual and pagina <= max_paginas:
        print(f"  Raspando página {pagina}: {url_atual}")

        response = requests.get(url_atual, headers=headers)
        soup = BeautifulSoup(response.content, 'html.parser')

        livros = extrair_livros_pagina(url_atual)
        todos_livros.extend(livros)

        url_atual = extrair_proxima_pagina(soup)
        pagina += 1

        time.sleep(0.3)  # Pausa educada entre requisições

    print(f"\nTotal de livros coletados: {len(todos_livros)}")
    salvar_csv(todos_livros, 'livros_parte2.csv')

parte2()

"""# **PARTE 3 — THREADS (paralelismo)**

**Conceitos novos:**
 - concurrent.futures.ThreadPoolExecutor → pool de threads
 - executor.map() → distribui tarefas entre as threads
 - threading.Lock() → evita condição de corrida no CSV

**Por que threads aqui?**
- Cada requisição HTTP passa a maior parte do tempo
- ESPERANDO a resposta do servidor (I/O).
- Com threads, enquanto uma thread espera, outra já busca a próxima página — economizando tempo.

"""

csv_lock = threading.Lock()  # Garante que só 1 thread escreve no CSV por vez
MAX_THREADS = 5


def montar_urls_paginas(total_paginas=10):
    """Monta a lista de URLs de todas as páginas que queremos raspar."""
    urls = [BASE_URL]  # Página 1
    for i in range(2, total_paginas + 1):
        urls.append(f"{BASE_URL}catalogue/page-{i}.html")
    return urls


def raspar_e_salvar_pagina(url):
    """Função executada por cada thread: raspa uma página e salva no CSV."""
    try:
        livros = extrair_livros_pagina(url)

        # Lock garante que duas threads não escrevem ao mesmo tempo
        with csv_lock:
            with open('livros_parte3.csv', mode='a', newline='', encoding='utf-8') as f:
                writer = csv.DictWriter(f, fieldnames=['titulo', 'preco', 'disponibilidade', 'rating'])
                writer.writerows(livros)

        print(f"  ✅ {len(livros)} livros extraídos de: {url}")

    except Exception as e:
        print(f"  ❌ Erro em {url}: {e}")


def parte3(total_paginas=10):
    print("=" * 50)
    print(f"PARTE 3 — Scraping com threads ({MAX_THREADS} threads, {total_paginas} páginas)")
    print("=" * 50)

    # Cria o CSV com o cabeçalho antes de iniciar as threads
    with open('livros_parte3.csv', mode='w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=['titulo', 'preco', 'disponibilidade', 'rating'])
        writer.writeheader()

    urls = montar_urls_paginas(total_paginas)

    start = time.time()

    # ThreadPoolExecutor cria um pool com MAX_THREADS threads
    # executor.map distribui as URLs entre as threads automaticamente
    with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_THREADS) as executor:
        executor.map(raspar_e_salvar_pagina, urls)

    elapsed = time.time() - start
    print(f"\n⏱️  Tempo com {MAX_THREADS} threads: {elapsed:.2f}s")
    print(f"✅ Arquivo salvo: livros_parte3.csv")

parte3()

"""# **COMPARAÇÃO: COM vs SEM threads**"""

def parte3_comparacao(total_paginas=10):
    print("=" * 50)
    print("Comparação: sequencial vs threads")
    print("=" * 50)

    urls = montar_urls_paginas(total_paginas)

    # Sequencial
    start = time.time()
    for url in urls:
        extrair_livros_pagina(url)
        time.sleep(0.1)
    tempo_sequencial = time.time() - start
    print(f"  Sequencial:  {tempo_sequencial:.2f}s")

    # Com threads
    start = time.time()
    with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_THREADS) as executor:
        executor.map(extrair_livros_pagina, urls)
    tempo_threads = time.time() - start
    print(f"  Com threads: {tempo_threads:.2f}s")

    ganho = tempo_sequencial / tempo_threads
    print(f"\n  🚀 Threads foram {ganho:.1f}x mais rápidas!")

parte3_comparacao()